/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KidsIndexRouteImport } from './routes/kids/index'
import { Route as ParentKidsRouteImport } from './routes/parent/kids'
import { Route as ParentJobsRouteImport } from './routes/parent/jobs'
import { Route as ParentDashboardRouteImport } from './routes/parent/dashboard'
import { Route as ParentChoresRouteImport } from './routes/parent/chores'
import { Route as ParentBankRouteImport } from './routes/parent/bank'
import { Route as ParentApprovalsRouteImport } from './routes/parent/approvals'
import { Route as KidsKidIdRouteImport } from './routes/kids/$kidId'
import { Route as KidsKidIdIndexRouteImport } from './routes/kids/$kidId/index'
import { Route as KidsKidIdJobsRouteImport } from './routes/kids/$kidId/jobs'
import { Route as KidsKidIdBankRouteImport } from './routes/kids/$kidId/bank'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIndexRoute = KidsIndexRouteImport.update({
  id: '/kids/',
  path: '/kids/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentKidsRoute = ParentKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => ParentRoute,
} as any)
const ParentJobsRoute = ParentJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChoresRoute = ParentChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => ParentRoute,
} as any)
const ParentBankRoute = ParentBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => ParentRoute,
} as any)
const ParentApprovalsRoute = ParentApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ParentRoute,
} as any)
const KidsKidIdRoute = KidsKidIdRouteImport.update({
  id: '/kids/$kidId',
  path: '/kids/$kidId',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsKidIdIndexRoute = KidsKidIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KidsKidIdRoute,
} as any)
const KidsKidIdJobsRoute = KidsKidIdJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => KidsKidIdRoute,
} as any)
const KidsKidIdBankRoute = KidsKidIdBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => KidsKidIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/kids/$kidId': typeof KidsKidIdRouteWithChildren
  '/parent/approvals': typeof ParentApprovalsRoute
  '/parent/bank': typeof ParentBankRoute
  '/parent/chores': typeof ParentChoresRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/jobs': typeof ParentJobsRoute
  '/parent/kids': typeof ParentKidsRoute
  '/kids/': typeof KidsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kids/$kidId/bank': typeof KidsKidIdBankRoute
  '/kids/$kidId/jobs': typeof KidsKidIdJobsRoute
  '/kids/$kidId/': typeof KidsKidIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/parent/approvals': typeof ParentApprovalsRoute
  '/parent/bank': typeof ParentBankRoute
  '/parent/chores': typeof ParentChoresRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/jobs': typeof ParentJobsRoute
  '/parent/kids': typeof ParentKidsRoute
  '/kids': typeof KidsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kids/$kidId/bank': typeof KidsKidIdBankRoute
  '/kids/$kidId/jobs': typeof KidsKidIdJobsRoute
  '/kids/$kidId': typeof KidsKidIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/kids/$kidId': typeof KidsKidIdRouteWithChildren
  '/parent/approvals': typeof ParentApprovalsRoute
  '/parent/bank': typeof ParentBankRoute
  '/parent/chores': typeof ParentChoresRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/jobs': typeof ParentJobsRoute
  '/parent/kids': typeof ParentKidsRoute
  '/kids/': typeof KidsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kids/$kidId/bank': typeof KidsKidIdBankRoute
  '/kids/$kidId/jobs': typeof KidsKidIdJobsRoute
  '/kids/$kidId/': typeof KidsKidIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/parent'
    | '/signup'
    | '/kids/$kidId'
    | '/parent/approvals'
    | '/parent/bank'
    | '/parent/chores'
    | '/parent/dashboard'
    | '/parent/jobs'
    | '/parent/kids'
    | '/kids/'
    | '/api/auth/$'
    | '/kids/$kidId/bank'
    | '/kids/$kidId/jobs'
    | '/kids/$kidId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/parent'
    | '/signup'
    | '/parent/approvals'
    | '/parent/bank'
    | '/parent/chores'
    | '/parent/dashboard'
    | '/parent/jobs'
    | '/parent/kids'
    | '/kids'
    | '/api/auth/$'
    | '/kids/$kidId/bank'
    | '/kids/$kidId/jobs'
    | '/kids/$kidId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/parent'
    | '/signup'
    | '/kids/$kidId'
    | '/parent/approvals'
    | '/parent/bank'
    | '/parent/chores'
    | '/parent/dashboard'
    | '/parent/jobs'
    | '/parent/kids'
    | '/kids/'
    | '/api/auth/$'
    | '/kids/$kidId/bank'
    | '/kids/$kidId/jobs'
    | '/kids/$kidId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRouteWithChildren
  SignupRoute: typeof SignupRoute
  KidsKidIdRoute: typeof KidsKidIdRouteWithChildren
  KidsIndexRoute: typeof KidsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/': {
      id: '/kids/'
      path: '/kids'
      fullPath: '/kids/'
      preLoaderRoute: typeof KidsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/kids': {
      id: '/parent/kids'
      path: '/kids'
      fullPath: '/parent/kids'
      preLoaderRoute: typeof ParentKidsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/jobs': {
      id: '/parent/jobs'
      path: '/jobs'
      fullPath: '/parent/jobs'
      preLoaderRoute: typeof ParentJobsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/chores': {
      id: '/parent/chores'
      path: '/chores'
      fullPath: '/parent/chores'
      preLoaderRoute: typeof ParentChoresRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/bank': {
      id: '/parent/bank'
      path: '/bank'
      fullPath: '/parent/bank'
      preLoaderRoute: typeof ParentBankRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/approvals': {
      id: '/parent/approvals'
      path: '/approvals'
      fullPath: '/parent/approvals'
      preLoaderRoute: typeof ParentApprovalsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/kids/$kidId': {
      id: '/kids/$kidId'
      path: '/kids/$kidId'
      fullPath: '/kids/$kidId'
      preLoaderRoute: typeof KidsKidIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$kidId/': {
      id: '/kids/$kidId/'
      path: '/'
      fullPath: '/kids/$kidId/'
      preLoaderRoute: typeof KidsKidIdIndexRouteImport
      parentRoute: typeof KidsKidIdRoute
    }
    '/kids/$kidId/jobs': {
      id: '/kids/$kidId/jobs'
      path: '/jobs'
      fullPath: '/kids/$kidId/jobs'
      preLoaderRoute: typeof KidsKidIdJobsRouteImport
      parentRoute: typeof KidsKidIdRoute
    }
    '/kids/$kidId/bank': {
      id: '/kids/$kidId/bank'
      path: '/bank'
      fullPath: '/kids/$kidId/bank'
      preLoaderRoute: typeof KidsKidIdBankRouteImport
      parentRoute: typeof KidsKidIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ParentRouteChildren {
  ParentApprovalsRoute: typeof ParentApprovalsRoute
  ParentBankRoute: typeof ParentBankRoute
  ParentChoresRoute: typeof ParentChoresRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentJobsRoute: typeof ParentJobsRoute
  ParentKidsRoute: typeof ParentKidsRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentApprovalsRoute: ParentApprovalsRoute,
  ParentBankRoute: ParentBankRoute,
  ParentChoresRoute: ParentChoresRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentJobsRoute: ParentJobsRoute,
  ParentKidsRoute: ParentKidsRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface KidsKidIdRouteChildren {
  KidsKidIdBankRoute: typeof KidsKidIdBankRoute
  KidsKidIdJobsRoute: typeof KidsKidIdJobsRoute
  KidsKidIdIndexRoute: typeof KidsKidIdIndexRoute
}

const KidsKidIdRouteChildren: KidsKidIdRouteChildren = {
  KidsKidIdBankRoute: KidsKidIdBankRoute,
  KidsKidIdJobsRoute: KidsKidIdJobsRoute,
  KidsKidIdIndexRoute: KidsKidIdIndexRoute,
}

const KidsKidIdRouteWithChildren = KidsKidIdRoute._addFileChildren(
  KidsKidIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRouteWithChildren,
  SignupRoute: SignupRoute,
  KidsKidIdRoute: KidsKidIdRouteWithChildren,
  KidsIndexRoute: KidsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
